import 'package:flutfest/logic/models/event_model.dart';
import 'package:flutfest/theme.dart';

class DummyEvents {
  static const int version = 1;

  static List<EventModel> events = [
    // Past Events
    EventModel(
      image: '${AppTheme.eventDirectory}marriage.png',
      eventId: 'dummy_marriage',
      title: 'Wedding Celebration',
      description: 'A wonderful wedding event.',
      startDate: DateTime(2027, 4, 10, 18, 0),
      endDate: DateTime(2027, 4, 10, 23, 0),
      location: 'Cairo',
      joinedUserIds: [],
      isUpcomingForDemo: true,
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}birthday.png',
      eventId: 'dummy_birthday',
      title: 'Birthday Party',
      description: 'A fun birthday celebration.',
      startDate: DateTime(2029, 4, 15, 17, 0),
      endDate: DateTime(2029, 4, 15, 22, 0),
      location: 'Alexandria',
      joinedUserIds: [],
      isUpcomingForDemo: true,
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}graduation.png',
      eventId: 'dummy_graduation',
      title: 'Graduation Ceremony',
      description: 'An inspiring graduation event.',
      startDate: DateTime(2024, 2, 20, 10, 0),
      endDate: DateTime(2024, 2, 20, 14, 0),
      location: 'Giza',
      joinedUserIds: [],
      isUpcomingForDemo: false,
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}engagement.png',
      eventId: 'dummy_engagement',
      title: 'Engagement Party',
      description: 'A beautiful engagement celebration.',
      startDate: DateTime(2027, 1, 25, 19, 0),
      endDate: DateTime(2027, 1, 25, 23, 0),
      location: 'Aswan',
      joinedUserIds: [],
      isUpcomingForDemo: true,
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}dinner.png',
      eventId: 'dummy_dinner',
      title: 'Dinner Gathering',
      description: 'A cozy dinner with friends and family.',
      startDate: DateTime(2023, 12, 31, 20, 0),
      endDate: DateTime(2023, 12, 31, 23, 59),
      location: 'Luxor',
      joinedUserIds: [],
      isUpcomingForDemo: false,
    ),
    // Upcoming Events
    EventModel(
      image: '${AppTheme.eventDirectory}concert.jpeg',
      eventId: 'dummy_concert',
      title: 'Music Concert',
      description: 'A thrilling music concert.',
      startDate: DateTime(2028, 10, 1, 18, 0),
      endDate: DateTime(2028, 10, 1, 23, 0),
      location: 'Cairo',
      isUpcomingForDemo: true,
      joinedUserIds: [],
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}festival.jpeg',
      eventId: 'dummy_festival',
      title: 'Cultural Festival',
      description: 'A vibrant cultural festival.',
      startDate: DateTime(2029, 10, 15, 10, 0),
      endDate: DateTime(2029, 10, 17, 22, 0),
      location: 'Alexandria',
      isUpcomingForDemo: true,
      joinedUserIds: [],
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}seminar.jpeg',
      eventId: 'dummy_seminar',
      title: 'Business Seminar',
      description: 'An informative business seminar.',
      startDate: DateTime(2024, 11, 1, 9, 0),
      endDate: DateTime(2024, 11, 1, 17, 0),
      location: 'Giza',
      isUpcomingForDemo: false,
      joinedUserIds: [],
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}exhibition.jpeg',
      eventId: 'dummy_exhibition',
      title: 'Art Exhibition',
      description: 'A stunning art exhibition.',
      startDate: DateTime(2024, 11, 15, 10, 0),
      endDate: DateTime(2024, 11, 20, 18, 0),
      location: 'Aswan',
      isUpcomingForDemo: false,
      joinedUserIds: [],
    ),
    EventModel(
      image: '${AppTheme.eventDirectory}charity_gala.jpeg',
      eventId: 'dummy_charity_gala',
      title: 'Charity Gala',
      description: 'A luxurious charity gala.',
      startDate: DateTime(2024, 12, 1, 19, 0),
      endDate: DateTime(2024, 12, 1, 23, 0),
      location: 'Luxor',
      isUpcomingForDemo: false,
      joinedUserIds: [],
    ),
  ];
}
